# Generated by Django 3.1.3 on 2020-11-16 02:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.CharField(max_length=20)),
                ('testId', models.CharField(max_length=15)),
                ('score', models.IntegerField()),
                ('answerSheet', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img')),
            ],
        ),
    ]
