# Generated by Django 3.1.3 on 2020-11-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0003_auto_20201116_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='answerKey',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
