# Generated by Django 3.1.3 on 2020-11-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0004_students_answerkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='correctMarks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testset',
            name='negativeMarks',
            field=models.FloatField(default=0.25),
            preserve_default=False,
        ),
    ]
